on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions: {}

jobs:
  build:
    timeout-minutes: 2
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "27.1"
          - "28.2"
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Emacs
        uses: purcell/setup-emacs@b3884972d55f850449e43be74de08f9a97aa3f34
        with:
          version: ${{ matrix.emacs-version }}
      - name: Test
        run: ./test.sh
