on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "27.1"
          - "28.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Emacs ${{ matrix.emacs-version }}
        uses: purcell/setup-emacs@11969ffc35972d0aa1a439489e99b4b61a60917c
        with:
          version: ${{ matrix.emacs-version }}
      - name: Test
        run: ./test.sh
