on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "27.1"
          - "28.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Emacs ${{ matrix.emacs-version }}
        uses: purcell/setup-emacs@8802e801f0eb15c6c602c4e5d1ddb5a0ff20b82d
        with:
          version: ${{ matrix.emacs-version }}
      - name: Test
        run: ./test.sh
